import streamlit as st
import ai
import random


HOUSES = [
    {
        'district': 'LAMBETH',
        'type': 'Flat/Maisonette',
        'age': 'New',
        'duration': 'Leasehold',
        'size': 42,
        'habitable_rooms': 2,
        'price': 355000
    },
    {
        'district': 'TEST VALLEY',
        'type': 'Semi-detached',
        'age': 'New',
        'duration': 'Freehold',
        'size': 72,
        'habitable_rooms': 4,
        'price': 267000
    },
    {
        'district': 'WEST NORTHAMPTONSHIRE',
        'type': 'Terraced',
        'age': 'New',
        'duration': 'Freehold',
        'size': 87,
        'habitable_rooms': 5,
        'price': 210000
    }
]


def fill_values(house: dict):
    st.session_state.random_size = house['size']
    st.session_state.random_rooms = house['habitable_rooms']
    st.session_state.random_duration = house['duration']
    st.session_state.random_age = house['age']
    st.session_state.random_type = house['type']
    st.session_state.random_district = house['district']
    st.rerun()


model = ai.load_model()

st.set_page_config(
    page_title="Property Price Evaluation")
st.title("Automated Property Price Evaluation in England and Wales")

col1, col2, col3 = st.columns([1, 1, 1])

with col1:
    fill_1 = st.button(f"Fill Example 1, real price £{HOUSES[0]['price']:,}")
with col2:
    fill_2 = st.button(f"Fill Example 2, real price £{HOUSES[1]['price']:,}")
with col3:
    fill_3 = st.button(f"Fill Example 3, real price £{HOUSES[2]['price']:,}")


if fill_1:
    fill_values(HOUSES[0])
if fill_2:
    fill_values(HOUSES[1])
if fill_3:
    fill_values(HOUSES[2])

size = st.number_input("Size of the property (in square meters):",
                       min_value=0, max_value=10000,
                       value=st.session_state.get('random_size', 50))

habitable_rooms = st.number_input("Number of habitable rooms:",
                                  min_value=0, max_value=20,
                                  value=st.session_state.get(
                                      'random_rooms', 2))
duration = st.radio(
    "What is the duration type?",
    ["Leasehold", "Freehold"],
    index=["Leasehold", "Freehold"].index(st.session_state.get('random_duration',
                                                               'Leasehold')),
)

age = st.radio(
    "Is the property old or new?",
    ["Old", "New"],
    index=["Old", "New"].index(st.session_state.get('random_age',
                                                    'Old')),
)

type = st.radio(
    "What is the property type?",
    ["Detached", "Semi-detached", "Terraced", "Flat/Maisonette", "Other"],
    index=["Detached", "Semi-detached", "Terraced", "Flat/Maisonette", "Other"].index(st.session_state.get('random_type',
                                                                                                           'Detached')),
)

districts = ['ADUR',
             'ALLERDALE',
             'AMBER VALLEY',
             'ARUN',
             'ASHFIELD',
             'ASHFORD',
             'AYLESBURY VALE',
             'BABERGH',
             'BARKING AND DAGENHAM',
             'BARNET',
             'BARNSLEY',
             'BARROW-IN-FURNESS',
             'BASILDON',
             'BASINGSTOKE AND DEANE',
             'BASSETLAW',
             'BATH AND NORTH EAST SOMERSET',
             'BEDFORD',
             'BEXLEY',
             'BIRMINGHAM',
             'BLABY',
             'BLACKBURN WITH DARWEN',
             'BLACKPOOL',
             'BLAENAU GWENT',
             'BOLSOVER',
             'BOLTON',
             'BOSTON',
             'BOURNEMOUTH',
             'BOURNEMOUTH, CHRISTCHURCH AND POOLE',
             'BRACKNELL FOREST',
             'BRADFORD',
             'BRAINTREE',
             'BRECKLAND',
             'BRENT',
             'BRENTWOOD',
             'BRIDGEND',
             'BRIGHTON AND HOVE',
             'BROADLAND',
             'BROMLEY',
             'BROMSGROVE',
             'BROXBOURNE',
             'BROXTOWE',
             'BUCKINGHAMSHIRE',
             'BURNLEY',
             'BURY',
             'CAERPHILLY',
             'CALDERDALE',
             'CAMBRIDGE',
             'CAMDEN',
             'CANNOCK CHASE',
             'CANTERBURY',
             'CARDIFF',
             'CARLISLE',
             'CARMARTHENSHIRE',
             'CASTLE POINT',
             'CENTRAL BEDFORDSHIRE',
             'CEREDIGION',
             'CHARNWOOD',
             'CHELMSFORD',
             'CHELTENHAM',
             'CHERWELL',
             'CHESHIRE EAST',
             'CHESHIRE WEST AND CHESTER',
             'CHESTERFIELD',
             'CHICHESTER',
             'CHILTERN',
             'CHORLEY',
             'CHRISTCHURCH',
             'CITY OF BRISTOL',
             'CITY OF DERBY',
             'CITY OF KINGSTON UPON HULL',
             'CITY OF LONDON',
             'CITY OF NOTTINGHAM',
             'CITY OF PETERBOROUGH',
             'CITY OF PLYMOUTH',
             'CITY OF WESTMINSTER',
             'COLCHESTER',
             'CONWY',
             'COPELAND',
             'CORBY',
             'CORNWALL',
             'COTSWOLD',
             'COUNTY DURHAM',
             'COVENTRY',
             'CRAVEN',
             'CRAWLEY',
             'CROYDON',
             'CUMBERLAND',
             'DACORUM',
             'DARLINGTON',
             'DARTFORD',
             'DAVENTRY',
             'DENBIGHSHIRE',
             'DERBYSHIRE DALES',
             'DONCASTER',
             'DORSET',
             'DOVER',
             'DUDLEY',
             'EALING',
             'EAST CAMBRIDGESHIRE',
             'EAST DEVON',
             'EAST DORSET',
             'EAST HAMPSHIRE',
             'EAST HERTFORDSHIRE',
             'EAST LINDSEY',
             'EAST NORTHAMPTONSHIRE',
             'EAST RIDING OF YORKSHIRE',
             'EAST STAFFORDSHIRE',
             'EAST SUFFOLK',
             'EASTBOURNE',
             'EASTLEIGH',
             'EDEN',
             'ELMBRIDGE',
             'ENFIELD',
             'EPPING FOREST',
             'EPSOM AND EWELL',
             'EREWASH',
             'EXETER',
             'FAREHAM',
             'FENLAND',
             'FLINTSHIRE',
             'FOLKESTONE AND HYTHE',
             'FOREST HEATH',
             'FOREST OF DEAN',
             'FYLDE',
             'GATESHEAD',
             'GEDLING',
             'GLOUCESTER',
             'GOSPORT',
             'GRAVESHAM',
             'GREAT YARMOUTH',
             'GREENWICH',
             'GUILDFORD',
             'GWYNEDD',
             'HACKNEY',
             'HALTON',
             'HAMBLETON',
             'HAMMERSMITH AND FULHAM',
             'HARBOROUGH',
             'HARINGEY',
             'HARLOW',
             'HARROGATE',
             'HARROW',
             'HART',
             'HARTLEPOOL',
             'HASTINGS',
             'HAVANT',
             'HAVERING',
             'HEREFORDSHIRE',
             'HERTSMERE',
             'HIGH PEAK',
             'HILLINGDON',
             'HINCKLEY AND BOSWORTH',
             'HORSHAM',
             'HOUNSLOW',
             'HUNTINGDONSHIRE',
             'HYNDBURN',
             'IPSWICH',
             'ISLE OF ANGLESEY',
             'ISLE OF WIGHT',
             'ISLES OF SCILLY',
             'ISLINGTON',
             'KENSINGTON AND CHELSEA',
             'KETTERING',
             "KING'S LYNN AND WEST NORFOLK",
             'KINGSTON UPON THAMES',
             'KIRKLEES',
             'KNOWSLEY',
             'LAMBETH',
             'LANCASTER',
             'LEEDS',
             'LEICESTER',
             'LEWES',
             'LEWISHAM',
             'LICHFIELD',
             'LINCOLN',
             'LIVERPOOL',
             'LUTON',
             'MAIDSTONE',
             'MALDON',
             'MALVERN HILLS',
             'MANCHESTER',
             'MANSFIELD',
             'MEDWAY',
             'MELTON',
             'MENDIP',
             'MERTHYR TYDFIL',
             'MERTON',
             'MID DEVON',
             'MID SUFFOLK',
             'MID SUSSEX',
             'MIDDLESBROUGH',
             'MILTON KEYNES',
             'MOLE VALLEY',
             'MONMOUTHSHIRE',
             'NEATH PORT TALBOT',
             'NEW FOREST',
             'NEWARK AND SHERWOOD',
             'NEWCASTLE UPON TYNE',
             'NEWCASTLE-UNDER-LYME',
             'NEWHAM',
             'NEWPORT',
             'NORTH DEVON',
             'NORTH DORSET',
             'NORTH EAST DERBYSHIRE',
             'NORTH EAST LINCOLNSHIRE',
             'NORTH HERTFORDSHIRE',
             'NORTH KESTEVEN',
             'NORTH LINCOLNSHIRE',
             'NORTH NORFOLK',
             'NORTH NORTHAMPTONSHIRE',
             'NORTH SOMERSET',
             'NORTH TYNESIDE',
             'NORTH WARWICKSHIRE',
             'NORTH WEST LEICESTERSHIRE',
             'NORTH YORKSHIRE',
             'NORTHAMPTON',
             'NORTHUMBERLAND',
             'NORWICH',
             'NUNEATON AND BEDWORTH',
             'OADBY AND WIGSTON',
             'OLDHAM',
             'OXFORD',
             'PEMBROKESHIRE',
             'PENDLE',
             'POOLE',
             'PORTSMOUTH',
             'POWYS',
             'PRESTON',
             'PURBECK',
             'READING',
             'REDBRIDGE',
             'REDCAR AND CLEVELAND',
             'REDDITCH',
             'REIGATE AND BANSTEAD',
             'RHONDDA CYNON TAFF',
             'RIBBLE VALLEY',
             'RICHMOND UPON THAMES',
             'RICHMONDSHIRE',
             'ROCHDALE',
             'ROCHFORD',
             'ROSSENDALE',
             'ROTHER',
             'ROTHERHAM',
             'RUGBY',
             'RUNNYMEDE',
             'RUSHCLIFFE',
             'RUSHMOOR',
             'RUTLAND',
             'RYEDALE',
             'SALFORD',
             'SANDWELL',
             'SCARBOROUGH',
             'SEDGEMOOR',
             'SEFTON',
             'SELBY',
             'SEVENOAKS',
             'SHEFFIELD',
             'SHEPWAY',
             'SHROPSHIRE',
             'SLOUGH',
             'SOLIHULL',
             'SOMERSET',
             'SOMERSET WEST AND TAUNTON',
             'SOUTH BUCKS',
             'SOUTH CAMBRIDGESHIRE',
             'SOUTH DERBYSHIRE',
             'SOUTH GLOUCESTERSHIRE',
             'SOUTH HAMS',
             'SOUTH HOLLAND',
             'SOUTH KESTEVEN',
             'SOUTH LAKELAND',
             'SOUTH NORFOLK',
             'SOUTH NORTHAMPTONSHIRE',
             'SOUTH OXFORDSHIRE',
             'SOUTH RIBBLE',
             'SOUTH SOMERSET',
             'SOUTH STAFFORDSHIRE',
             'SOUTH TYNESIDE',
             'SOUTHAMPTON',
             'SOUTHEND-ON-SEA',
             'SOUTHWARK',
             'SPELTHORNE',
             'ST ALBANS',
             'ST EDMUNDSBURY',
             'ST HELENS',
             'STAFFORD',
             'STAFFORDSHIRE MOORLANDS',
             'STEVENAGE',
             'STOCKPORT',
             'STOCKTON-ON-TEES',
             'STOKE-ON-TRENT',
             'STRATFORD-ON-AVON',
             'STROUD',
             'SUFFOLK COASTAL',
             'SUNDERLAND',
             'SURREY HEATH',
             'SUTTON',
             'SWALE',
             'SWANSEA',
             'SWINDON',
             'TAMESIDE',
             'TAMWORTH',
             'TANDRIDGE',
             'TAUNTON DEANE',
             'TEIGNBRIDGE',
             'TENDRING',
             'TEST VALLEY',
             'TEWKESBURY',
             'THANET',
             'THE VALE OF GLAMORGAN',
             'THREE RIVERS',
             'THURROCK',
             'TONBRIDGE AND MALLING',
             'TORBAY',
             'TORFAEN',
             'TORRIDGE',
             'TOWER HAMLETS',
             'TRAFFORD',
             'TUNBRIDGE WELLS',
             'UTTLESFORD',
             'VALE OF WHITE HORSE',
             'WAKEFIELD',
             'WALSALL',
             'WALTHAM FOREST',
             'WANDSWORTH',
             'WARRINGTON',
             'WARWICK',
             'WATFORD',
             'WAVENEY',
             'WAVERLEY',
             'WEALDEN',
             'WELLINGBOROUGH',
             'WELWYN HATFIELD',
             'WEST BERKSHIRE',
             'WEST DEVON',
             'WEST DORSET',
             'WEST LANCASHIRE',
             'WEST LINDSEY',
             'WEST NORTHAMPTONSHIRE',
             'WEST OXFORDSHIRE',
             'WEST SOMERSET',
             'WEST SUFFOLK',
             'WESTMORLAND AND FURNESS',
             'WEYMOUTH AND PORTLAND',
             'WIGAN',
             'WILTSHIRE',
             'WINCHESTER',
             'WINDSOR AND MAIDENHEAD',
             'WIRRAL',
             'WOKING',
             'WOKINGHAM',
             'WOLVERHAMPTON',
             'WORCESTER',
             'WORTHING',
             'WREKIN',
             'WREXHAM',
             'WYCHAVON',
             'WYCOMBE',
             'WYRE',
             'WYRE FOREST',
             'YORK']

district = st.selectbox(
    "Select the district:",
    districts,
    index=districts.index(st.session_state.get('random_district',
                                               'ADUR'))
)

submit = st.button("Predict Property Price")

if submit:
    price = ai.predict(
        model, [district, type, "N" if age == "New" else "O", duration, size, habitable_rooms])

    st.success(f"The evaluated property price is: £{price:,.0f}")
